### ISSUE TITLE
The plugin return label "null".

### ISSUE THREAD

**Issue by ve3** [arthurgouveia/prettyCheckable#76]
HTML copy from your website.

``` html
<div class="input-wrapper">
              <label for="Test1">Right positioned label (no params)</label>
              <input type="checkbox" class="prettyCheckable" value="1" id="Test1" name="Test1" checked/>
            </div>

            <div class="input-wrapper">
              <input type="checkbox" class="prettyCheckable" value="3" id="TestDisabled" name="TestDisabled" disabled data-label='Existing "disabled" attribute'>
            </div>
```

``` js
$('.prettyCheckable').prettyCheckable();
```

![prettycheckbox](https://cloud.githubusercontent.com/assets/1568262/3121653/d18cd668-e75e-11e3-9f96-0ee3029c2a47.jpg)

Jquery 2.x
prettyCheckable: 2.1.2
Bootstrap 3.1.1
Firefox 29.0.1

**Comment by arthurgouveia** [comment]
Are you calling .prettyCheckable on each?

Check the documentation. You need a for loop and instantiate it on each
checkable.

**Comment by beaterpc** [comment]
same problem here.
http://jsfiddle.net/beater/mrf3U/

**Comment by arthurgouveia** [comment]
http://jsfiddle.net/mrf3U/1/

**Comment by ve3** [comment]
loop and instantiate it on each checkable works.

**Comment by beaterpc** [comment]
data-label is required then?
"If informed, this will create a label attached to the input."
_IF_

**Comment by arthurgouveia** [comment]
I believe this bug was introduced with the label auto detection. Are you using any labels at all for your input?

Can you open an issue explaining that if no label is provided, either by inline options or auto detected, the null is showing up?

**Comment by baltazorr** [comment]
I think, It was fixed in my pull request https://github.com/arthurgouveia/prettyCheckable/pull/81

**Comment by 0xadri** [comment]
This is still NOT fixed.

See this fiddle https://jsfiddle.net/eqsfsrh3/

**Comment by baltazorr** [comment]
My pull request was rejected because there was a lot of changes. If you need my changes you can merge this request locally on your machine.

**Comment by 0xadri** [comment]
Thanks a lot, but I'd rather stick with the official version for now.

I used this trick for now:
1. add a custom class to the parent div, via data-customClass attribute such as: `data-customClass="no-label"`
2. add the relevant CSS such as: `.no-label label {  display: none;}`

Simple enough to be an acceptable work around in my opinion.

**Comment by 0xadri** [comment]
Ended up using a combination of JS & CSS.

On the Javascript/jQuery side:

```
$('input:checkbox, input:radio').each(function(){
  $(this).prettyCheckable();
  var labelValue = $(this).data('label') || '';
  if( (!labelValue || 0 === labelValue.length) ){
    $(this).parent().addClass('no-label');
  }
});
```

And on the CSS side:

```
.no-label label {
  display: none !important;
}
```

**Comment by ufocruz** [comment]
I fixed it using an label for each input and inserted an for on each label.
